---
- stat:
    path: "{{ cassandra_truststore }}"
  register: truststore_result

- name: Import Cassandra CA certificate to keystore
  shell: "keytool -keystore truststore.p12 -alias CassandraCARoot -importcert -file {{ cassandra_ca_cert }} -keypass cassandra -storepass cassandra -storetype pkcs12 -noprompt"
  args:
    chdir: "{{ cassandra_ca_dir }}"
    executable: /bin/bash
  when: truststore_result.stat.exists == false  
