---
- name: Create facts
  set_fact: 
    seeds: "{{ groups['cassandra_nodes'] | map('extract', hostvars, ['ansible_default_ipv4', 'address']) | join(',') }}"
    node_ip: "{{ ansible_default_ipv4.address }}"

- name: Generate cassandra.yaml
  become: yes
  template:
    src: "cassandra-{{ cassandra_version }}.yaml.j2"
    dest: /etc/cassandra/cassandra.yaml

- name: Copy Cassandra truststore
  become: yes
  copy:
    src: "{{ ca_dir }}/truststore.p12"
    dest: /etc/cassandra/truststore.p12
  when: client_encryption_enabled or server_encryption_internode_encryption != "none"

- name: Copy keystore
  become: yes
  copy:
    src: "{{ ca_dir }}/{{ inventory_hostname }}/keystore.p12"
    dest: /etc/cassandra/keystore.p12
  when: client_encryption_enabled or server_encryption_internode_encryption != "none"

- name: Configure cassandra-rackdc.properties
  become: yes
  template:
    src: cassandra-rackdc.properties.j2
    dest: /etc/cassandra/cassandra-rackdc.properties

- name: Start Cassandra
  become: yes
  service:
    name: cassandra
    state: restarted
  when: restart_cassandra_after_config_update | bool
