---
- name: Create Client CA and truststore
  hosts: master
  connection: local
  gather_facts: False
  vars:
   ca_dir: /tmp/cassandra-tls-lab/clients
   ca_name: ClientCA
  roles:
    - tls_truststore

- name: Create Cassandra CA and truststore
  hosts: master
  connection: local
  gather_facts: False
  vars:
   ca_dir: /tmp/cassandra-tls-lab/cassandra
   ca_name: CassandraCA
  roles:
    - tls_truststore

- name: Import Client CA cert into node truststore
  hosts: master
  connection: local
  gather_facts: False
  vars:
    only_import_cert: True
    ca_dir: /tmp/cassandra-tls-lab/cassandra
    ca_name: ClientCA
    ca_cert: /tmp/cassandra-tls-lab/clients/ca.crt
  roles:
    - tls_truststore

- name: Import Cassandra CA cert into client truststore
  hosts: master
  connection: local
  gather_facts: False
  vars:
    only_import_cert: True
    ca_dir: /tmp/cassandra-tls-lab/clients
    ca_name: CassandraCA
    ca_cert: /tmp/cassandra-tls-lab/cassandra/ca.crt
  roles:
    - tls_truststore

- name: Create client keystores
  hosts: clients
  gather_facts: False
  connection: local
  vars:
    ca_dir: /tmp/cassandra-tls-lab/clients
    ca_name: ClientCA
    ssl_extensions_enabled: False
  roles:
    - tls_keystore

- name: Create node keystores
  hosts: cassandra_nodes
  gather_facts: False
  connection: local
  vars:
    ca_dir: /tmp/cassandra-tls-lab/cassandra
    ca_name: CassandraCA
    ssl_extensions_enabled: False
  roles:
    - tls_keystore

- name: Enable client encryption (optional)
  hosts: cassandra_nodes
  gather_facts: True
  vars:
    ca_dir: /tmp/cassandra-tls-lab/cassandra
    cluster_name: tlp_lab
    client_encryption_enabled: true
    client_encryption_optional: true
    client_encryption_keystore: /etc/cassandra/keystore.p12
    client_encryption_truststore: /etc/cassandra/keystore.p12
    client_encryption_store_type: PKCS12
  roles:
    #- node_keystores
    - cassandra_configuration
