---
- name: Create Cassandra CA
  hosts: master
  connection: local
  gather_facts: False
  vars:
    tls_reset: True
  roles:
    - tls_delete
    - cassandra_ca

- name: Update node configurations
  hosts: cassandra_nodes
  gather_facts: True
  vars:
    cluster_name: tlp_lab
    internode_encryption_enabled: True
    #ssl_extensions_disabled: True
    ssl_extensions_enabled: False
  roles:
    - node_keystores
    - cassandra_configuration
