---
- name: Copy Cassandra truststore
  become: yes
  copy: 
    src: "{{ cassandra_ca_dir  }}/truststore.p12"
    dest: /etc/cassandra/truststore.p12

- name: Copy keystore
  become: yes
  copy:
    src: "{{ cassandra_ca_dir }}/{{ inventory_hostname }}/keystore.p12"
    dest: /etc/cassandra/keystore.p12
